// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7gyoJh-VMHGbkemvwAUShlERuKZLvuI',
    appId: '1:872876666707:web:4cd8d782f439e59aafbba6',
    messagingSenderId: '872876666707',
    projectId: 'dj77-1b00c',
    authDomain: 'dj77-1b00c.firebaseapp.com',
    storageBucket: 'dj77-1b00c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-s4OCpiv-cLqIQJZKt6Z_sYlZ2snO4tE',
    appId: '1:872876666707:android:d89a51ce1bfbccfeafbba6',
    messagingSenderId: '872876666707',
    projectId: 'dj77-1b00c',
    storageBucket: 'dj77-1b00c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzcCvCIiSycZKJp-QR7Mx1YCeu84p9ow',
    appId: '1:872876666707:ios:c439ae455d39e9dfafbba6',
    messagingSenderId: '872876666707',
    projectId: 'dj77-1b00c',
    storageBucket: 'dj77-1b00c.appspot.com',
    iosClientId: '872876666707-lrtfaloug2vrtrjreo4s9cqhsr2bjfan.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelltonFlutterTraining',
  );
}
